version: "2.4"

services:
  redis:
    image: redis
    ports:
      - "5379:6379"
        #es:
        # image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
        #environment:
        # - discovery.type=single-node
        # - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        # ports:
        #- "6200:9200"
        # - "6300:9300"
        #healthcheck:
        # test: ["CMD", "curl", "-f", "localhost:9200/_cluster/health"]
        #interval: 30s
        #timeout: 10s
        #retries: 4
      # db:
      # image: postgres
      #volumes:
      # - ./db-data:/var/lib/postgresql/data
      #ports:
      # - "6432:5432"
      # environment:
      # - POSTGRES_DB=registry
      # - POSTGRES_USER=postgres
      # - POSTGRES_PASSWORD=postgres
  registry:
    image: dockerhub/sunbird-rc-core:pre-v0.0.8-7
    volumes:
      - ${PWD}/schemas:/home/sunbirdrc/config/public/_schemas

    environment:
      - connectionInfo_uri=jdbc:postgresql://10.0.136.159:5432/registry
      - connectionInfo_username=registry_admin
      - connectionInfo_password=registry
      - elastic_search_connection_url=10.0.136.159:9200
      - search_provider=dev.sunbirdrc.registry.service.ElasticSearchService
      - sunbird_sso_publickey=
      - sunbird_sso_realm=sunbird-rc
      - sunbird_sso_url=http://keycloak:8080/auth
      - sunbird_sso_admin_client_id=admin-api
      - sunbird_sso_client_id=registry-frontend
      - sunbird_sso_admin_client_secret=
      - claims_url=http://claim-ms:8082
      - sign_url=http://certificate-signer:8079/sign
      - verify_url=http://certificate-signer:8079/verify
      - signature_enabled=true
      - pdf_url=http://certificate-api:8078/api/v1/certificatePDF
      - template_base_url=http://registry:8081/api/v1/templates/ #Looks for certificate templates for pdf copy of the signed certificate
      - sunbird_keycloak_user_set_password=true
      - filestorage_connection_url=
      - filestorage_access_key=
      - filestorage_secret_key=
      - filestorage_bucket_key=
      - registry_base_apis_enable=false
      - sunbird_keycloak_user_password=
        # - logging.level.root=DEBUG
      - enable_external_templates=true
      - authentication_enabled=true
    ports:
      - "6083:8081"
        # depends_on:
        # es:
        # condition: service_healthy
        #db:
        # condition: service_started
  keycloak:
    image: dockerhub/ndear-keycloak:pre-v0.0.8-3
    volumes:
      - ${PWD}/imports:/opt/jboss/keycloak/imports
    environment:
      - KEYCLOAK_LOGO=https://raw.githubusercontent.com/tejash-jl/ref-sunbird-certificate-demo/async_mode/assets/issuance_portal.svg
      - KEYCLOAK_PORTAL_TITLE=Issuance
      - KEYCLOAK_PORTAL_SUB_TITLE=Issue documents that are digitally verifiable
      - SIGN_UP_LINK=/form/signup
      - DB_VENDOR=postgres
      - DB_ADDR=10.0.136.159
      - DB_PORT=5432
      - DB_DATABASE=registry
      - DB_USER=registry_admin
      - DB_PASSWORD=registry
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/opt/jboss/keycloak/imports/realm-export.json
      - PROXY_ADDRESS_FORWARDING=true
      - REGISTER_URL=http://localhost:4200/form/signup
    healthcheck:
      test:
         ["CMD-SHELL", "curl -f http://localhost:9990/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "8080:8080"
      - "6990:9990"
        # depends_on:
        #db:
        #condition: service_started
        #claim-ms:
        #image: dockerhub/sunbird-rc-claim-ms:v0.0.5
        # environment:
        # - connectionInfo_uri=jdbc:postgresql://10.0.136.159:5432/registry
        #- connectionInfo_username=registry_admin
        #- connectionInfo_password=registry
        #- sunbirdrc_url=http://registry:8081
        # ports:
        # - "6084:8082"
        #depends_on:
            #db:
            #condition: service_started
            #registry:
            #condition: service_started
  certificate-signer:
    image: dockerhub/sunbird-rc-certificate-signer:pre-v0.0.8-2
    environment:
      - PORT=8079
    ports:
      - "6079:8079"
  certificate-api:
    image: dockerhub/sunbird-rc-certificate-api
    volumes:
      - ${PWD}/scripts:/scripts
    entrypoint: ["sh", "/scripts/docker-entrypoint.sh"]
    environment:
      - PORT=8078
      - QR_TYPE=W3C-VC
      - CERTIFICATE_DOMAIN_URL=https://aastrika-stage.tarento.com
    ports:
      - "6078:8078"
  verification-ui:
    image: tejashjl/verification
    ports:
      - "6080:80"
  file-storage:
    image: quay.io/minio/minio
    volumes:
      - ${HOME}/minio/data:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=Admin@14#
    command: server --address 0.0.0.0:9000 --console-address 0.0.0.0:9001 /data
    ports:
      - "6000:9000"
      - "6001:9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
